/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        headline: ['Newsreader', 'Georgia', 'serif'],
        oi: ['var(--font-oi)', 'Georgia', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        grotesk: ['var(--font-grotesk)', 'Roboto Flex', 'sans-serif'],
        syne: ['Inter', 'sans-serif'],
        dm: ['Inter', 'sans-serif'],
      },
      colors: {
        // Microsoft brand
        'ms-blue': '#0078D4',
        'ms-accent': '#106EBE',
        'ms-dark': '#0A1628',
        'ms-navy': '#1E3A5F',
        'ms-card': '#FFFFFF',
        'ms-green': '#107C10',
        'ms-yellow': '#D83B01',
        'ms-purple': '#5C2D91',
        'ms-red': '#A4262C',
        'ms-orange': '#CA5010',
        // Editorial design tokens (from HTML)
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface': '#f0f4ff',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f5f8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-variant': '#e1e3e4',
        'surface-tint': '#0060ab',
        'on-surface': '#191c1d',
        'on-surface-variant': '#404752',
        'on-background': '#191c1d',
        'background': '#f8f9fa',
        'primary': '#005faa',
        'primary-container': '#0078d4',
        'primary-fixed': '#d3e3ff',
        'primary-fixed-dim': '#a3c9ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#ffffff',
        'on-primary-fixed': '#001c39',
        'on-primary-fixed-variant': '#004883',
        'inverse-primary': '#a3c9ff',
        'secondary': '#5e5e5e',
        'secondary-container': '#e4e2e2',
        'secondary-fixed': '#e4e2e2',
        'secondary-fixed-dim': '#c8c6c6',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#646464',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#474747',
        'tertiary': '#2c6094',
        'tertiary-container': '#4879af',
        'tertiary-fixed': '#d2e4ff',
        'tertiary-fixed-dim': '#9fcaff',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffffff',
        'on-tertiary-fixed': '#001d37',
        'on-tertiary-fixed-variant': '#08497c',
        'outline': '#717783',
        'outline-variant': '#c0c7d4',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        '3xl': '1rem',
        full: '0.75rem',
      },
      boxShadow: {
        'card': '0 4px 6px -1px rgba(0,0,0,0.01), 0 10px 15px -3px rgba(0,0,0,0.03)',
        'card-hover': '0 4px 6px -1px rgba(0,0,0,0.02), 0 10px 15px -3px rgba(0,0,0,0.05)',
        'nav': '0 1px 2px 0 rgba(0,0,0,0.05)',
        'dropdown': '0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -2px rgba(0,0,0,0.1)',
      },
    },
  },
  plugins: [],
}
