import { fetchMicrosoftFeeds } from '../../lib/feeds'
import { readFileSync, existsSync } from 'fs'
import { join } from 'path'
import Link from 'next/link'

function makeSlug(title) {
  return String(title || '')
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .substring(0, 80)
    .replace(/-$/, '')
}

export const revalidate = 1800 // Revalidate every 30 minutes

export const metadata = {
  title: 'Live Microsoft Updates — Latest News & Announcements | Independent Blog',
  description: 'Real-time Microsoft updates across Windows, Azure, Copilot, Microsoft 365, Security. Independent coverage updated every 30 minutes.',
  robots: { index: true, follow: true },
}

function timeAgo(dateStr) {
  const now = new Date()
  const date = new Date(dateStr)
  const diff = Math.floor((now - date) / 1000)
  if (diff < 60) return 'just now'
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`
  if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`
  if (diff < 604800) return `${Math.floor(diff / 86400)}d ago`
  return date.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })
}

const categoryColors = {
  windows: 'bg-ms-green/15 text-ms-green',
  azure: 'bg-ms-blue/15 text-ms-blue',
  security: 'bg-[#00BCF2]/15 text-[#00BCF2]',
  office365: 'bg-ms-orange/15 text-ms-orange',
  'power-platform': 'bg-ms-yellow/15 text-ms-yellow',
  copilot: 'bg-ms-accent/15 text-ms-accent',
  fabric: 'bg-purple-400/15 text-purple-400',
  general: 'bg-ms-accent/15 text-ms-accent',
}

const categoryLabels = {
  windows: 'Windows',
  azure: 'Azure',
  security: 'Security',
  office365: 'Office 365',
  'power-platform': 'Power Platform',
  copilot: 'Copilot / AI',
  fabric: 'Fabric',
  general: 'General',
}

export default async function LiveUpdatesPage() {
  // 1. Try live-updates.json first (generated by fetch script)
  let items = []
  try {
    const livePath = join(process.cwd(), 'data', 'live-updates.json')
    if (existsSync(livePath)) {
      const data = JSON.parse(readFileSync(livePath, 'utf8'))
      items = data.items || []
    }
  } catch {}

  // 2. Fall back to RSS feeds if JSON is empty
  if (items.length === 0) {
    try {
      const feeds = await fetchMicrosoftFeeds()
      items = feeds.slice(0, 60).map((a) => ({
        title: a.title,
        summary: a.description?.substring(0, 220) || '',
        date: a.pubDate,
        category: a.feedCategory || 'general',
        sourceUrl: a.link,
        slug: a.slug || '',
      }))
    } catch {}
  }

  const categories = ['all', 'windows', 'azure', 'security', 'office365', 'copilot', 'power-platform', 'fabric']

  return (
    <main className="max-w-7xl mx-auto px-4 py-10">
      {/* Page header */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-3">
          <span className="flex items-center gap-1.5 bg-ms-red/15 text-ms-red text-xs font-bold px-3 py-1 rounded-full">
            <span className="w-2 h-2 bg-ms-red rounded-full animate-pulse"></span>
            LIVE
          </span>
          <span className="text-xs text-[var(--text-muted)] font-dm">Updated every 30 minutes</span>
        </div>
        <h1 className="font-syne font-extrabold text-3xl md:text-4xl text-[var(--text-primary)] tracking-tight mb-2">
          Live Microsoft Updates
        </h1>
        <p className="text-[var(--text-secondary)] font-dm text-base max-w-2xl">
          Independent coverage of the latest Microsoft announcements across all products.
          Every item links to the official Microsoft source for verification.
        </p>
      </div>

      {/* Category filter pills (client-side via search params would need client component; keep server-simple here) */}
      <div className="flex flex-wrap gap-2 mb-8">
        {categories.map((cat) => (
          <span
            key={cat}
            className={`text-xs font-medium px-3 py-1.5 rounded-full border border-[var(--border)] ${
              cat === 'all'
                ? 'bg-ms-blue text-white border-ms-blue'
                : 'bg-ms-card text-[var(--text-secondary)] hover:border-ms-blue/40'
            }`}
          >
            {cat === 'all' ? 'All Updates' : categoryLabels[cat] || cat}
          </span>
        ))}
      </div>

          {/* Updates grid */}
      {items.length === 0 ? (
        <div className="bg-ms-card rounded-2xl border border-[var(--border)] p-12 text-center">
          <p className="text-[var(--text-muted)] font-dm">Loading live updates...</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
          {items.map((item, i) => {
            const colorClass = categoryColors[item.category] || categoryColors.general
            const label = categoryLabels[item.category] || item.category
            const internalSlug = item.slug || makeSlug(item.title)

            return (
              <div key={i} className="group relative bg-ms-card rounded-xl border border-[var(--border)] overflow-hidden flex flex-col hover:border-ms-blue/40 transition-all duration-200 hover:-translate-y-0.5">
                {/* Full card link */}
                <Link href={`/live/${internalSlug}`} className="absolute inset-0 z-0" aria-label={item.title} />

                {/* Image */}
                {item.image && (
                  <div className="w-full aspect-[16/9] overflow-hidden bg-ms-dark">
                    <img
                      src={item.image}
                      alt={item.title}
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                      loading="lazy"
                    />
                  </div>
                )}

                <div className="relative z-10 p-5 flex flex-col gap-3 flex-1">
                  {/* Badge + time */}
                  <div className="flex items-center justify-between">
                    <span className={`text-[10px] font-bold px-2.5 py-0.5 rounded-full ${colorClass}`}>
                      {label}
                    </span>
                    <span className="text-[10px] text-[var(--text-muted)] font-dm">{timeAgo(item.date)}</span>
                  </div>

                  {/* Title */}
                  <h2 className="font-syne font-bold text-sm text-[var(--text-primary)] leading-snug tracking-tight line-clamp-3 flex-1 group-hover:text-ms-accent transition-colors">
                    {item.title}
                  </h2>

                  {/* Summary */}
                  {item.summary && (
                    <p className="text-xs text-[var(--text-secondary)] font-dm leading-relaxed line-clamp-2">
                      {item.summary}
                    </p>
                  )}

                  {/* Footer row */}
                  <div className="flex items-center gap-3 pt-1 mt-auto border-t border-[var(--border)]">
                    <span className="text-xs font-semibold text-ms-accent">Read article →</span>
                    {item.sourceUrl && (
                      <a
                        href={item.sourceUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="relative z-20 text-[10px] text-[var(--text-muted)] hover:text-[var(--text-primary)] flex items-center gap-1 ml-auto transition-colors"
                        title="Verify from official Microsoft source"
                      >
                        <svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                          <path d="M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6"/>
                          <polyline points="15 3 21 3 21 9"/>
                          <line x1="10" y1="14" x2="21" y2="3"/>
                        </svg>
                        Verify from Microsoft
                      </a>
                    )}
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      )}

      {/* Footer note */}
      <p className="text-xs text-[var(--text-muted)] font-dm text-center mt-10">
        This is an independent blog. All updates are sourced from official Microsoft RSS feeds.
        Always verify from the official Microsoft link before taking action.
      </p>
    </main>
  )
}
